<?php

namespace Database\Seeders\Asset;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $date = now();
        $countries = [
            [
                'name' => 'Afghanistan',
                'iso' => 'AF',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Albania',
                'iso' => 'AL',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Algeria',
                'iso' => 'DZ',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Andorra',
                'iso' => 'AD',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Angola',
                'iso' => 'AO',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Antigua and Barbuda',
                'iso' => 'AG',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Argentina',
                'iso' => 'AR',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Armenia',
                'iso' => 'AM',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Australia',
                'iso' => 'AU',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Austria',
                'iso' => 'AT',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Azerbaijan',
                'iso' => 'AZ',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Bahamas',
                'iso' => 'BS',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Bahrain',
                'iso' => 'BH',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Bangladesh',
                'iso' => 'BD',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Barbados',
                'iso' => 'BB',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Belarus',
                'iso' => 'BY',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Belgium',
                'iso' => 'BE',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Belize',
                'iso' => 'BZ',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Benin',
                'iso' => 'BJ',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Bhutan',
                'iso' => 'BT',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Bolivia',
                'iso' => 'BO',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Bosnia and Herzegovina',
                'iso' => 'BA',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Botswana',
                'iso' => 'BW',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Brazil',
                'iso' => 'BR',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Brunei',
                'iso' => 'BN',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Bulgaria',
                'iso' => 'BG',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Burkina Faso',
                'iso' => 'BF',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Burundi',
                'iso' => 'BI',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => "Côte d'Ivoire",
                'iso' => 'CI',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Cabo Verde',
                'iso' => 'CV',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Cambodia',
                'iso' => 'KH',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Cameroon',
                'iso' => 'CM',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Canada',
                'iso' => 'CA',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Central African Republic',
                'iso' => 'CF',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Chad',
                'iso' => 'TD',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Chile',
                'iso' => 'CL',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'China',
                'iso' => 'CN',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Colombia',
                'iso' => 'CO',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Comoros',
                'iso' => 'KM',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Congo (Congo-Brazzaville)',
                'iso' => 'CG',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Costa Rica',
                'iso' => 'CR',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Croatia',
                'iso' => 'HR',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Cuba',
                'iso' => 'CU',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Cyprus',
                'iso' => 'CY',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Czechia (Czech Republic)',
                'iso' => 'CZ',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Democratic Republic of the Congo',
                'iso' => 'CD',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Denmark',
                'iso' => 'DK',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Djibouti',
                'iso' => 'DJ',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Dominica',
                'iso' => 'DM',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Dominican Republic',
                'iso' => 'DO',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Ecuador',
                'iso' => 'EC',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Egypt',
                'iso' => 'EG',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'El Salvador',
                'iso' => 'SV',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Equatorial Guinea',
                'iso' => 'GQ',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Eritrea',
                'iso' => 'ER',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Estonia',
                'iso' => 'EE',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Eswatini (fmr. Swaziland)',
                'iso' => 'SZ',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Ethiopia',
                'iso' => 'ET',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Fiji',
                'iso' => 'FJ',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Finland',
                'iso' => 'FI',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'France',
                'iso' => 'FR',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Gabon',
                'iso' => 'GA',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Gambia',
                'iso' => 'GM',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Georgia',
                'iso' => 'GE',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Germany',
                'iso' => 'DE',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Ghana',
                'iso' => 'GH',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Greece',
                'iso' => 'GR',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Grenada',
                'iso' => 'GD',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Guatemala',
                'iso' => 'GT',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Guinea',
                'iso' => 'GN',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Guinea-Bissau',
                'iso' => 'GW',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Guyana',
                'iso' => 'GY',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Haiti',
                'iso' => 'HT',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Holy See',
                'iso' => 'VA',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Honduras',
                'iso' => 'HN',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Hungary',
                'iso' => 'HU',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Iceland',
                'iso' => 'IS',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'India',
                'iso' => 'IN',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Indonesia',
                'iso' => 'ID',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Iran',
                'iso' => 'IR',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Iraq',
                'iso' => 'IQ',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Ireland',
                'iso' => 'IE',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Israel',
                'iso' => 'IL',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Italy',
                'iso' => 'IT',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Jamaica',
                'iso' => 'JM',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Japan',
                'iso' => 'JP',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Jordan',
                'iso' => 'JO',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Kazakhstan',
                'iso' => 'KZ',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Kenya',
                'iso' => 'KE',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Kiribati',
                'iso' => 'KI',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Kuwait',
                'iso' => 'KW',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Kyrgyzstan',
                'iso' => 'KG',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Laos',
                'iso' => 'LA',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Latvia',
                'iso' => 'LV',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Lebanon',
                'iso' => 'LB',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Lesotho',
                'iso' => 'LS',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Liberia',
                'iso' => 'LR',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Libya',
                'iso' => 'LY',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Liechtenstein',
                'iso' => 'LI',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Lithuania',
                'iso' => 'LT',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Luxembourg',
                'iso' => 'LU',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Madagascar',
                'iso' => 'MG',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Malawi',
                'iso' => 'MW',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Malaysia',
                'iso' => 'MY',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Maldives',
                'iso' => 'MV',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Mali',
                'iso' => 'ML',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Malta',
                'iso' => 'MT',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Marshall Islands',
                'iso' => 'MH',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Mauritania',
                'iso' => 'MR',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Mauritius',
                'iso' => 'MU',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Mexico',
                'iso' => 'MX',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Micronesia',
                'iso' => 'FM',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Moldova',
                'iso' => 'MD',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Monaco',
                'iso' => 'MC',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Mongolia',
                'iso' => 'MN',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Montenegro',
                'iso' => 'ME',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Morocco',
                'iso' => 'MA',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Mozambique',
                'iso' => 'MZ',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Myanmar (formerly Burma)',
                'iso' => 'MM',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Namibia',
                'iso' => 'NA',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Nauru',
                'iso' => 'NR',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Nepal',
                'iso' => 'NP',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Netherlands',
                'iso' => 'NL',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'New Zealand',
                'iso' => 'NZ',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Nicaragua',
                'iso' => 'NI',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Niger',
                'iso' => 'NE',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Nigeria',
                'iso' => 'NG',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'North Korea',
                'iso' => 'KP',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'North Macedonia (formerly Macedonia)',
                'iso' => 'MK',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Norway',
                'iso' => 'NO',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Oman',
                'iso' => 'OM',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Pakistan',
                'iso' => 'PK',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Palau',
                'iso' => 'PW',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Palestine State',
                'iso' => 'PS',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Panama',
                'iso' => 'PA',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Papua New Guinea',
                'iso' => 'PG',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Paraguay',
                'iso' => 'PY',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Peru',
                'iso' => 'PE',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Philippines',
                'iso' => 'PH',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Poland',
                'iso' => 'PL',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Portugal',
                'iso' => 'PT',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Qatar',
                'iso' => 'QA',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Romania',
                'iso' => 'RO',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Russia',
                'iso' => 'RU',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Rwanda',
                'iso' => 'RW',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Saint Kitts and Nevis',
                'iso' => 'KN',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Saint Lucia',
                'iso' => 'LC',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Saint Vincent and the Grenadines',
                'iso' => 'VC',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Samoa',
                'iso' => 'WS',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'San Marino',
                'iso' => 'SM',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Sao Tome and Principe',
                'iso' => 'ST',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Saudi Arabia',
                'iso' => 'SA',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Senegal',
                'iso' => 'SN',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Serbia',
                'iso' => 'RS',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Seychelles',
                'iso' => 'SC',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Sierra Leone',
                'iso' => 'SL',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Singapore',
                'iso' => 'SG',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Slovakia',
                'iso' => 'SK',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Slovenia',
                'iso' => 'SI',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Solomon Islands',
                'iso' => 'SB',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Somalia',
                'iso' => 'SO',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'South Africa',
                'iso' => 'ZA',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'South Korea',
                'iso' => 'KR',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'South Sudan',
                'iso' => 'SS',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Spain',
                'iso' => 'ES',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Sri Lanka',
                'iso' => 'LK',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Sudan',
                'iso' => 'SD',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Suriname',
                'iso' => 'SR',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Sweden',
                'iso' => 'SE',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Switzerland',
                'iso' => 'CH',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Syria',
                'iso' => 'SY',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Tajikistan',
                'iso' => 'TJ',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Tanzania',
                'iso' => 'TZ',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Thailand',
                'iso' => 'TH',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Timor-Leste',
                'iso' => 'TL',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Togo',
                'iso' => 'TG',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Tonga',
                'iso' => 'TO',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Trinidad and Tobago',
                'iso' => 'TT',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Tunisia',
                'iso' => 'TN',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Turkey',
                'iso' => 'TR',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Turkmenistan',
                'iso' => 'TM',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Tuvalu',
                'iso' => 'TV',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Uganda',
                'iso' => 'UG',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Ukraine',
                'iso' => 'UA',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'United Arab Emirates',
                'iso' => 'AE',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'United Kingdom',
                'iso' => 'GB',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'United States of America',
                'iso' => 'US',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Uruguay',
                'iso' => 'UY',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Uzbekistan',
                'iso' => 'UZ',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Vanuatu',
                'iso' => 'VU',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Venezuela',
                'iso' => 'VE',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Vietnam',
                'iso' => 'VN',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Yemen',
                'iso' => 'YE',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Zambia',
                'iso' => 'ZM',
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'name' => 'Zimbabwe',
                'iso' => 'ZW',
                'created_at' => $date,
                'updated_at' => $date,
            ],
        ];

        Country::insert($countries);
    }
}
